# -*- coding: utf-8 -*-
"""German Data Risk Homework3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Ke-4XciBd4cFeByZsKi6YdMeHl3MX_O
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

df=pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/statlog/german/german.data",sep=" ",header=None)

df.head()

df.set_axis(['0','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20'], axis=1)

df.isna().sum()
# no null values

y = df.pop(20)

y = y.replace({1: True, 2: False})

y.head()

dummies = pd.get_dummies(df[[0, 2, 3,5,6,8,9,11,13,14,16,18,19]], prefix=['col0', 'col2', 'col3','col5','col6','col8','col9','col11','col13','col14','col16','col18','col19'])

df = df.drop(columns=[0, 2, 3,5,6,8,9,11,13,14,16,18,19])

df = pd.concat([df, dummies], axis=1)

df.head()

X = df

X= X.rename(str,axis="columns")

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=0, stratify=y
)

model = LogisticRegression(max_iter=10000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))